name: Push (build and local tests)

on:
  push: {}

jobs:
  basic:
    runs-on: [ self-hosted ]
    steps:
      - name: Store context in variable
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "Full github context: ${GITHUB_CONTEXT}"

      - name: Show github context directly
        run: | 
          echo 'Full github context: ${{ toJSON(github) }}'
